
permalink: pretty

# RSS feed
gems:
- jekyll-feed


title: Dror Bogin's Site
tagline: 'Personal Website'
description: project updates
url:                 https://bogind.github.io/
baseurl:             ''
paginate: 5


# About/contact
author:
  name:              Dror Bogin
  url:               
  email:             Bogind@post.bgu.ac.il
